"""A small byte-level BPE tokenizer with lossless UTF-8 round trips."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path


def _merge_pair(sequence: list[int], pair: tuple[int, int], new_id: int) -> list[int]:
    merged: list[int] = []
    index = 0
    while index < len(sequence):
        if index + 1 < len(sequence) and (sequence[index], sequence[index + 1]) == pair:
            merged.append(new_id)
            index += 2
        else:
            merged.append(sequence[index])
            index += 1
    return merged


class BPETokenizer:
    """Byte-BPE with optional frequent-character atoms and byte fallback."""

    def __init__(
        self,
        merges: list[tuple[int, int]] | None = None,
        extra_tokens: list[bytes] | None = None,
    ) -> None:
        self.merges = list(merges or [])
        self._token_bytes: list[bytes] = [bytes([value]) for value in range(256)]
        self._extra_token_ids: dict[str, int] = {}
        for payload in extra_tokens or []:
            if not payload or payload in self._token_bytes:
                raise ValueError("invalid or duplicate extra base token")
            try:
                text = payload.decode("utf-8", errors="strict")
            except UnicodeDecodeError as exc:
                raise ValueError("extra base tokens must be complete UTF-8") from exc
            if len(text) != 1:
                raise ValueError("extra base tokens must contain exactly one character")
            self._extra_token_ids[text] = len(self._token_bytes)
            self._token_bytes.append(payload)
        self.base_vocab_size = len(self._token_bytes)
        for left, right in self.merges:
            if left >= len(self._token_bytes) or right >= len(self._token_bytes):
                raise ValueError("invalid merge table: token referenced before creation")
            self._token_bytes.append(self._token_bytes[left] + self._token_bytes[right])

    @property
    def vocab_size(self) -> int:
        return len(self._token_bytes)

    @classmethod
    def train(
        cls,
        text: str,
        vocab_size: int = 512,
        min_pair_frequency: int = 2,
        char_vocab_size: int = 0,
    ) -> "BPETokenizer":
        if vocab_size < 256:
            raise ValueError("byte-level BPE requires vocab_size >= 256")
        if char_vocab_size < 0:
            raise ValueError("char_vocab_size cannot be negative")
        char_counts = Counter(char for char in text if "\u3400" <= char <= "\u9fff")
        char_budget = min(char_vocab_size, max(0, vocab_size - 256))
        frequent_chars = [
            char
            for char, _ in sorted(
                char_counts.items(), key=lambda item: (-item[1], item[0])
            )[:char_budget]
        ]
        extra_tokens = [char.encode("utf-8") for char in frequent_chars]
        char_ids = {char: 256 + index for index, char in enumerate(frequent_chars)}
        sequence: list[int] = []
        for char in text:
            token_id = char_ids.get(char)
            if token_id is None:
                sequence.extend(char.encode("utf-8"))
            else:
                sequence.append(token_id)
        merges: list[tuple[int, int]] = []
        base_vocab_size = 256 + len(extra_tokens)
        while base_vocab_size + len(merges) < vocab_size and len(sequence) > 1:
            counts = Counter(zip(sequence, sequence[1:]))
            if not counts:
                break
            pair, frequency = min(
                counts.items(), key=lambda item: (-item[1], item[0])
            )
            if frequency < min_pair_frequency:
                break
            new_id = base_vocab_size + len(merges)
            sequence = _merge_pair(sequence, pair, new_id)
            merges.append(pair)
        return cls(merges, extra_tokens)

    def encode(self, text: str) -> list[int]:
        sequence: list[int] = []
        for char in str(text):
            token_id = self._extra_token_ids.get(char)
            if token_id is None:
                sequence.extend(char.encode("utf-8"))
            else:
                sequence.append(token_id)
        for rank, pair in enumerate(self.merges):
            sequence = _merge_pair(sequence, pair, self.base_vocab_size + rank)
        return sequence

    def decode(self, ids: list[int]) -> str:
        return self.ids_to_bytes(ids).decode("utf-8", errors="replace")

    def ids_to_bytes(self, ids: list[int]) -> bytes:
        """Return the exact generated bytes without silently modifying them."""
        try:
            return b"".join(self._token_bytes[int(index)] for index in ids)
        except IndexError as exc:
            raise ValueError("token id is outside the vocabulary") from exc

    def token_bytes(self, token_id: int) -> bytes:
        try:
            return self._token_bytes[int(token_id)]
        except IndexError as exc:
            raise ValueError("token id is outside the vocabulary") from exc

    @staticmethod
    def advance_utf8_state(state: int, payload: bytes) -> int | None:
        """Advance a strict UTF-8 prefix state; ``None`` means an invalid byte.

        States 1--3 are ordinary continuation counts; 4--7 additionally encode
        UTF-8's restricted first continuation ranges for E0, ED, F0 and F4.
        This lets byte-level decoding reject invalid UTF-8 *before* sampling,
        without substituting replacement characters later.
        """
        if state not in set(range(8)):
            raise ValueError("invalid UTF-8 prefix state")
        for value in payload:
            if state:
                lower, upper, next_state = {
                    1: (0x80, 0xBF, 0),
                    2: (0x80, 0xBF, 1),
                    3: (0x80, 0xBF, 2),
                    4: (0xA0, 0xBF, 1),  # E0: no overlong 3-byte form
                    5: (0x80, 0x9F, 1),  # ED: exclude UTF-16 surrogates
                    6: (0x90, 0xBF, 2),  # F0: no overlong 4-byte form
                    7: (0x80, 0x8F, 2),  # F4: stay inside Unicode's range
                }[state]
                if not lower <= value <= upper:
                    return None
                state = next_state
            elif value <= 0x7F:
                continue
            elif 0xC2 <= value <= 0xDF:
                state = 1
            elif value == 0xE0:
                state = 4
            elif value == 0xED:
                state = 5
            elif 0xE1 <= value <= 0xEC or 0xEE <= value <= 0xEF:
                state = 2
            elif value == 0xF0:
                state = 6
            elif value == 0xF4:
                state = 7
            elif 0xF1 <= value <= 0xF3:
                state = 3
            else:
                return None
        return state

    def utf8_state_for_ids(self, ids: list[int]) -> int | None:
        state = 0
        for token_id in ids:
            state = self.advance_utf8_state(state, self.token_bytes(token_id))
            if state is None:
                return None
        return state

    def valid_next_tokens(self, state: int) -> tuple[list[int], dict[int, int]]:
        """Return token ids that preserve a valid UTF-8 prefix from ``state``."""
        transitions: dict[int, int] = {}
        for token_id, payload in enumerate(self._token_bytes):
            next_state = self.advance_utf8_state(state, payload)
            if next_state is not None:
                transitions[token_id] = next_state
        return list(transitions), transitions

    def decode_complete(self, ids: list[int]) -> tuple[str, int]:
        """Decode only through a complete UTF-8 boundary.

        Returns the strict decoded text and the number of trailing BPE tokens
        omitted because a fixed token budget ended in the middle of a code point.
        The caller can still save ``ids_to_bytes(ids)`` as the unmodified raw
        generation evidence.
        """
        usable = list(ids)
        trimmed = 0
        while usable:
            try:
                return self.ids_to_bytes(usable).decode("utf-8", errors="strict"), trimmed
            except UnicodeDecodeError:
                usable.pop()
                trimmed += 1
        return "", trimmed

    def save_pretrained(self, path: str | Path) -> None:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(
                {
                    "type": "byte_bpe",
                    "vocab_size": self.vocab_size,
                    "extra_tokens_hex": [
                        payload.hex()
                        for payload in self._token_bytes[256:self.base_vocab_size]
                    ],
                    "merges": [list(pair) for pair in self.merges],
                },
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )

    @classmethod
    def from_pretrained(cls, path: str | Path) -> "BPETokenizer":
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        extras = [bytes.fromhex(value) for value in payload.get("extra_tokens_hex", [])]
        return cls([tuple(map(int, pair)) for pair in payload["merges"]], extras)
